# Site settings
title: Story Hopper
url: http://story-hopper.com
baseurl: ''
description: Stories worth sharing

# Build
sass:
  style: compressed

# Misc
exclude: ['CNAME', 'LICENSE.md', 'README.md']
permalink: pretty

# Gems
gems:
  - jekyll-sitemap
